=== radiosmersh/selectbf/selectbf-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="selectbf-config">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="database">
					<xs:complexType>
						<xs:attribute name="user" type="xs:string" use="required"/>
						<xs:attribute name="password" type="xs:string" use="required"/>
						<xs:attribute name="database" type="xs:string" use="required"/>
						<xs:attribute name="port" type="xs:int" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="after-parsing"/>
				<xs:element name="archive-folder"/>
				<xs:element name="after-download"/>
				<xs:element name="delete-decompressed-xml-files" type="xs:boolean"/>
				<xs:element name="rename-at-error" type="xs:boolean"/>
				<xs:element name="log-bots"/>
				<xs:element name="trim-database">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:boolean">
								<xs:attribute name="days" type="xs:int" use="required"/>
								<xs:attribute name="keep-players" type="xs:boolean" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="skip-empty-rounds" type="xs:boolean"/>
				<xs:element name="lan-mode" type="xs:boolean"/>				
				<xs:element name="consistency-check" type="xs:boolean"/>
				<xs:element name="memory-safer" type="xs:boolean"/>
				<xs:element name="logs" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="dir" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:anyURI">
											<xs:attribute name="live" type="xs:boolean" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="ftp" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="host" type="xs:anyURI" use="required"/>
									<xs:attribute name="port" type="xs:string" use="required"/>
									<xs:attribute name="user" type="xs:string" use="required"/>
									<xs:attribute name="password" type="xs:string" use="required"/>
									<xs:attribute name="live" type="xs:boolean" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== radiosmersh/selectbf/config.xml
<selectbf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.selectbf.org/xsd/selectbf-config.xsd">
 <!--DATABASE CONFIGURATION-->
 <database user="user" password="password" database="database" port="3306">localhost</database>

 <!--FILE MANAGEMENT-->
 <after-parsing>remain</after-parsing>
 <archive-folder>\archive\</archive-folder>
 <after-download>remain</after-download>
 <delete-decompressed-xml-files>true</delete-decompressed-xml-files>
 <rename-at-error>false</rename-at-error>
 
 <!--DATA MANAGEMENT-->
 <log-bots>false</log-bots>
 <trim-database days="5" keep-players="false">false</trim-database>
 <skip-empty-rounds>false</skip-empty-rounds>
 <lan-mode>false</lan-mode>
 
 <!--OTHER STUFF-->
 <consistency-check>true</consistency-check>
 <memory-safer>true</memory-safer>
 
 <!--LOG SOURCES-->
 <!-- 
 	PLEASE NOTE: None of these are mandatory, if you don't want a source, delete it.
 	Also you can add as much sources as you want.
 --> 	
 <logs>
  <dir live="false">c:\battlefield\mods\bf1942\logs</dir>
  <ftp host="127.0.0.1" port="21" user="user" password="password" live="false">/mods/bf1942/logs</ftp>
 </logs>
</selectbf-config>

=== radiosmersh/selectbf/res/conf/config_docker.xml
<selectbf-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.selectbf.org/xsd/selectbf-config.xsd">
 <!--DATABASE CONFIGURATION-->
 <database user="${DB_USER}" password="${DB_PASSWORD}" database="${DB_DATABASE}" port="${DB_PORT}">mariadb</database>

 <!--FILE MANAGEMENT-->
 <after-parsing>archive</after-parsing>
 <archive-folder>/app/logs/archive</archive-folder>
 <after-download>remain</after-download>
 <delete-decompressed-xml-files>false</delete-decompressed-xml-files>
 <rename-at-error>false</rename-at-error>
 
 <!--DATA MANAGEMENT-->
 <log-bots>false</log-bots>
 <trim-database days="5" keep-players="false">false</trim-database>
 <skip-empty-rounds>true</skip-empty-rounds>
 <lan-mode>true</lan-mode>
 
 <!--OTHER STUFF-->
 <consistency-check>true</consistency-check>
 <memory-safer>true</memory-safer>
 
 <!--LOG SOURCES-->
 <!-- 
 	PLEASE NOTE: None of these are mandatory, if you don't want a source, delete it.
 	Also you can add as much sources as you want.
 --> 	
 <logs>
  <dir live="false">/app/logs</dir>
 </logs>
</selectbf-config>
